name: Build MP3TagEncodeFixer

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Автоматически выбирает последнюю версию
    
    - name: Install dependencies
      run: |
        python -m pip install mutagen pyinstaller
    
    - name: Build app
      run: |
        pyinstaller --onefile --windowed --name MP3TagEncodeFixer --target-arch universal2 MP3TagEncodeFixer.py
    
    - name: Remove quarantine
      run: |
        xattr -dr com.apple.quarantine dist/MP3TagEncodeFixer.app
    
    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg --volname "MP3TagEncodeFixer" MP3TagEncodeFixer.dmg dist/MP3TagEncodeFixer.app
    
    - uses: actions/upload-artifact@v4
      with:
        name: MP3TagEncodeFixer
        path: MP3TagEncodeFixer.dmg
